### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by KiraTuring** [smallXueTu/Rcon#2]
把插件放进plugins文件夹，启动mcl后插件并没有加载

mirai-console版本是2.7-M2

**Comment by HIM049** [comment]
插件没有被识别和加载。Mirai Console Loader version 1.2.1-de7b624

**Comment by smallXueTu** [comment]
感谢你的issues，Mirai是一个非常活跃的项目，导致该项目api的改动非常大。现在该项目API已经相对稳定，已经重写了该项目已经兼容最新的Mirai，如果还有需要欢迎使用和提出新的issues！
