### ISSUE TITLE
插件不会被框架识别

### ISSUE THREAD

**Issue by HIM049** [smallXueTu/Rcon#3]
插件没有被识别和加载。Mirai Console Loader version 1.2.1-de7b624

**Comment by smallXueTu** [comment]
感谢你的issues，Mirai是一个非常活跃的项目，导致该项目api的改动非常大。现在该项目API已经相对稳定，已经重写了该项目已经兼容最新的Mirai，如果还有需要欢迎使用和提出新的issues！
