### ISSUE TITLE
没有达到实际操作

### ISSUE THREAD

**Issue by unlomi** [smallXueTu/Rcon#5]
按着作者的操作 操作着，但是在qq群输入所设指令并没有反映，如果可以请发布一个视频教程或手把手教一下

**Comment by smallXueTu** [comment]
请检查服务器连通性、RCON是否正确配置、服务器防火墙问题、RCON端口是否允许开放、另外插件不会加载“示例.yml”

**Comment by smallXueTu** [comment]
插件做了个小更新 你可以使用"rcon add 备注"添加一个配置然后再"rcon reload"重载

**Comment by unlomi** [comment]
rcon add 的那个我已经弄好了，问题应该出在服务器上

**Comment by smallXueTu** [comment]
解决了吗 服务器那边是不是有防火墙啥的

**Comment by unlomi** [comment]
防火墙关了，我会的都试过了

**Comment by unlomi** [comment]
还是没有成功

**Comment by smallXueTu** [comment]
加个qq聊吧 2665337794
